# Generated by Django 3.0.6 on 2020-05-28 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_comment_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Author',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'managed': True, 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
