# Generated by Django 3.0.7 on 2020-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_post_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about_page',
            field=models.TextField(null=True),
        ),
    ]
