# Generated by Django 3.0.7 on 2020-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200725_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.AddField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
