# Generated by Django 3.0.7 on 2020-07-26 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_auto_20200726_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
