# Generated by Django 3.0.7 on 2020-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_author_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
